[package]
name = "patch-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bsdiff = "0.2.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.9"

[dev-dependencies]
tempfile = "3.23.0"
